# Generated by Django 4.1.5 on 2023-02-02 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(default='', max_length=33, null=True, verbose_name='科室名称')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '科室管理',
                'verbose_name_plural': '科室管理',
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('numbers_s', models.IntegerField(default=-1, verbose_name='开始用户ID')),
                ('numbers_e', models.IntegerField(default=-1, verbose_name='结束用户ID')),
                ('log', models.TextField(verbose_name='内容')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='创建日期')),
                ('is_active', models.SmallIntegerField(choices=[(1, '正常'), (2, '删除')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '日志',
                'verbose_name_plural': '日志',
                'db_table': 'Log',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(default='', max_length=33, null=True, verbose_name='职务')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='创建日期')),
                ('is_active', models.SmallIntegerField(choices=[(1, '正常'), (4, '禁用')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '职务管理',
                'verbose_name_plural': '职务管理',
                'db_table': 'Post',
            },
        ),
        migrations.CreateModel(
            name='Users_bao_an',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(default='', max_length=33, null=True, verbose_name='姓名')),
                ('gender', models.SmallIntegerField(choices=[(0, '男'), (1, '女'), (2, '未知')], default=2, verbose_name='性别')),
                ('counter', models.IntegerField(default=0, verbose_name='值班次数')),
                ('phone', models.CharField(max_length=32, null=True, verbose_name='手机号')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='创建日期')),
                ('is_active', models.SmallIntegerField(choices=[(1, '正常'), (2, '请假'), (3, '出差'), (4, '禁用')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '值班保安管理',
                'verbose_name_plural': '值班保安管理',
                'db_table': 'Users_bao_an',
            },
        ),
        migrations.CreateModel(
            name='Users_dai_ban',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(default='', max_length=33, null=True, verbose_name='姓名')),
                ('gender', models.SmallIntegerField(choices=[(0, '男'), (1, '女'), (2, '未知')], default=2, verbose_name='性别')),
                ('counter', models.IntegerField(default=0, verbose_name='值班次数')),
                ('phone', models.CharField(max_length=32, null=True, verbose_name='手机号')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='创建日期')),
                ('is_active', models.SmallIntegerField(choices=[(1, '正常'), (2, '请假'), (3, '出差'), (4, '禁用')], default=1, verbose_name='状态')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.department', verbose_name='科室')),
                ('post', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='index.post', verbose_name='职务')),
            ],
            options={
                'verbose_name': '带班管理',
                'verbose_name_plural': '带班管理',
                'db_table': 'Users_dai',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(default='', max_length=33, null=True, verbose_name='姓名')),
                ('gender', models.SmallIntegerField(choices=[(0, '男'), (1, '女'), (2, '未知')], default=2, verbose_name='性别')),
                ('counter', models.IntegerField(default=0, verbose_name='值班次数')),
                ('phone', models.CharField(max_length=32, null=True, verbose_name='手机号')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='创建日期')),
                ('is_active', models.SmallIntegerField(choices=[(1, '正常'), (2, '请假'), (3, '出差'), (4, '禁用')], default=1, verbose_name='状态')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.department', verbose_name='科室')),
                ('post', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='index.post', verbose_name='职务')),
            ],
            options={
                'verbose_name': '班员管理',
                'verbose_name_plural': '班员管理',
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('counter', models.IntegerField(default=0, verbose_name='值班次数')),
                ('type', models.SmallIntegerField(choices=[(1, '白班'), (2, '晚班')], default=2, verbose_name='类别')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='创建日期')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='index.users', verbose_name='班员')),
                ('user_dai', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='index.users_dai_ban', verbose_name='带班')),
            ],
            options={
                'verbose_name': '值班匹配',
                'verbose_name_plural': '值班匹配',
                'db_table': 'Matching',
            },
        ),
    ]
