# Generated by Django 4.1.5 on 2023-02-02 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='post',
        ),
        migrations.RemoveField(
            model_name='users_dai_ban',
            name='post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
